my_learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views


# template urls
app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('special/', views.special, name='special'),
]

my_learning_users/my_learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('logut/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

my_learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    # the next line extends the class to have more user attributes
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='basic_app/profile_pics', blank=True)

    def __str__(self):
        # self.user.username is the default attribute of User
        return self.user.username

my_learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

my_learning_users/basic_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm
# from django.contrib.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'basic_App/index.html')


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            # the next command hashes the password
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {'user_form': user_form,
                                                           'profile_form': profile_form,
                                                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed")
            print(f"Username: {username} and password {password}")
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'basic_app/login.html', {})


@login_required
def special(request):
    return HttpResponse("You are logged in")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

my_learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="navbar-nav">
                <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
                <a class="nav-item nav-link" href="{% url 'admin:index' %}">ADMIN</a>
                <a class="nav-item nav-link" href="{% url 'basic_app:special' %}">special</a>
                <!--<a class="nav-item nav-link" href="{% url 'basic_app:register' %}">Register</a>-->
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
                    <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
                {% endif %}
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

my_learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Django Level Five</h1>
    </div>
{% endblock %}

my_learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Please Login</h1>
        <form action="{% url 'basic_app:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="username"  name="username" placeholder="Enter username">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password">
            <input type="submit" value="Login">
        </form>
    </div>
{% endblock %}

my_learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register Here!</h1>
            <h3>Fill out the form:</h3>
            <!--{# enctype="multipart/form-data this is so we can upload data (images) }-->
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}